/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as IndexImport } from './pages/index'
import { Route as cesProfilesImport } from './pages/(ces)/profiles'
import { Route as asWorkspacesWorkspaceIdImport } from './pages/(as)/workspaces/$workspaceId'
import { Route as assearchSearchImport } from './pages/(as)/(search)/search'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const cesProfilesRoute = cesProfilesImport.update({
  path: '/profiles',
  getParentRoute: () => rootRoute,
} as any)

const asWorkspacesWorkspaceIdRoute = asWorkspacesWorkspaceIdImport.update({
  path: '/workspaces/$workspaceId',
  getParentRoute: () => rootRoute,
} as any)

const assearchSearchRoute = assearchSearchImport.update({
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(ces)/profiles': {
      preLoaderRoute: typeof cesProfilesImport
      parentRoute: typeof rootRoute
    }
    '/(as)/(search)/search': {
      preLoaderRoute: typeof assearchSearchImport
      parentRoute: typeof rootRoute
    }
    '/(as)/workspaces/$workspaceId': {
      preLoaderRoute: typeof asWorkspacesWorkspaceIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  cesProfilesRoute,
  assearchSearchRoute,
  asWorkspacesWorkspaceIdRoute,
])

/* prettier-ignore-end */
