// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './../apps/poc/src/app/__root'
import { Route as AppImport } from './../apps/poc/src/app/app'
import { Route as IndexDImport } from './../apps/poc/src/app/index.d'

// Create/Update Routes

const AppRoute = AppImport.update({
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexDRoute = IndexDImport.update({
  path: '/index/d',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/index/d': {
      preLoaderRoute: typeof IndexDImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([AppRoute, IndexDRoute])
